name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
	  - uses: actions/setup-go@v1
			with:
				go-version: 1.13
    - uses: actions/checkout@v1
    - run: go get -u golang.org/x/lint/golint
    - run: make clean generate
    - run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
	  - uses: actions/setup-go@v1
			with:
				go-version: 1.13
    - uses: actions/checkout@v1
    - run: make clean generate
    - run: make test
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - uses: actions/checkout@v1
    - env:
        HEROKU_API_KEY: {{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: arcane-waters-53217
      run: make deploy
