name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@v1
      - name: Install binaries
        run: |
          echo "::add-path::$(go env GOPATH)/bin"
          go get -u github.com/golang/mock/mockgen
          go get -u golang.org/x/lint/golint
      - run: make clean generate
      - run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install binaries
        run: |
          echo "::add-path::$(go env GOPATH)/bin"
          go get -u github.com/golang/mock/mockgen
      - run: make clean generate
      - run: make test
  create-deployment:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Create deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:owner/:repo/deployments
          owner: gobridge-kr
          repo: ${{ github.repository }}
          ref: $${{ github.sha }}
          description: Deploy request from GitHub workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
