name: CI

on:
  push:
    paths:
      - '!**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@v1
      - name: Install binaries
        run: |
          echo "::add-path::$(go env GOPATH)/bin"
          go get -u github.com/golang/mock/mockgen
          go get -u golang.org/x/lint/golint
      - run: make clean generate
      - run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install binaries
        run: |
          echo "::add-path::$(go env GOPATH)/bin"
          go get -u github.com/golang/mock/mockgen
      - run: make clean generate
      - run: make test
  create-deployment:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Parse repository name
        id: parse_repository_name
        run: |
          echo ::set-output name=OWNER::$(echo ${{ github.repository }} | cut -d '/' -f 1)
          echo ::set-output name=REPO::$(echo ${{ github.repository }} | cut -d '/' -f 2)
      - name: Create deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:owner/:repo/deployments
          owner: ${{ steps.parse_repository_name.outputs.OWNER }}
          repo: ${{ steps.parse_repository_name.outputs.REPO }}
          ref: ${{ github.sha }}
          required_contexts: '[]'
          description: Deploy request from GitHub workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_DEPLOY_TOKEN }}
